/**
 * Documentation generator.
 *
 * Rendering is pure: `renderDocs` turns a registry into an in-memory file map,
 * which `writeDocs` persists and `checkDocs` compares against disk. Nothing
 * here knows about any specific CLI, and every string comes from the same help
 * model the runtime help uses.
 */

import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { lintSchema } from '../core/lint.ts';
import type { LintOptions, LintReport } from '../core/lint.ts';
import { normalizeSchema } from '../core/schema.ts';
import type { CommandRegistry, RegistryNode } from '../core/schema.ts';
import type { CLISchema } from '../core/types.ts';
import { buildCommandHelp, buildGroupHelp, buildRootHelp } from '../help/model.ts';
import type { CommandHelp } from '../help/model.ts';
import { renderCommandMarkdown, renderCommandTree } from '../help/renderers/markdown.ts';

/** Banner written at the top of every generated file. */
export const GENERATED_BANNER =
  '<!-- Generated by `npm run docs`. Do not edit by hand; edit the CLI schema instead. -->';

export interface GenerateDocsOptions {
  /** The authored schema, or a registry you already normalized. */
  schema?: CLISchema;
  registry?: CommandRegistry;
  /** Directory generated files are written to. */
  outDir?: string;
  /** Root object name used in JS examples. Defaults to `cli`. */
  rootName?: string;
  /** Schema checks run before generating. Errors abort generation. */
  lint?: LintOptions | false;
}

/** A generated file, keyed by its path relative to `outDir`. */
export type GeneratedFiles = Map<string, string>;

function toRegistry(options: GenerateDocsOptions): CommandRegistry {
  if (options.registry) return options.registry;
  if (options.schema) return normalizeSchema(options.schema);
  throw new TypeError('generateDocs requires either a "schema" or a "registry".');
}

/** Top-level nodes become one file each: `commands/<name>.md`. */
function fileNameFor(node: RegistryNode): string {
  return `commands/${node.key}.md`;
}

function collectCommands(registry: CommandRegistry, node: RegistryNode, rootName: string): CommandHelp[] {
  const helps: CommandHelp[] = [];
  const command = registry.commands.get(node.path);
  if (command) helps.push(buildCommandHelp(registry, command, rootName));
  for (const child of node.children) helps.push(...collectCommands(registry, child, rootName));
  return helps;
}

function renderIndex(registry: CommandRegistry, nodes: readonly RegistryNode[], rootName: string): string {
  const root = buildRootHelp(registry);
  const sections: string[] = [GENERATED_BANNER, `# ${registry.binary} API reference`];

  if (registry.description) sections.push(registry.description);

  sections.push(`## Command tree\n\n\`\`\`text\n${renderCommandTree(registry)}\n\`\`\``);

  const rows = nodes.map((node) => {
    const group = registry.groups.get(node.path);
    const description = group?.description ?? registry.commands.get(node.path)?.description ?? '';
    return `| [\`${node.key}\`](./${fileNameFor(node)}) | ${description.replaceAll('|', '\\|')} |`;
  });
  sections.push(['## Commands', '', '| Group | Description |', '|---|---|', ...rows].join('\n'));

  sections.push(
    ['## All commands', '', ...root.commands.map((path) => `- \`${rootName}.${path}\``)].join('\n'),
  );

  return `${sections.join('\n\n')}\n`;
}

function renderNodeFile(registry: CommandRegistry, node: RegistryNode, rootName: string): string {
  const sections: string[] = [GENERATED_BANNER];
  const group = registry.groups.get(node.path);
  const commands = collectCommands(registry, node, rootName);

  // A top-level leaf command is its own page; no group preamble to repeat.
  if (!group && commands.length === 1) {
    sections.push(renderCommandMarkdown(commands[0] as CommandHelp, 1));
    return `${sections.join('\n\n')}\n`;
  }

  sections.push(`# ${node.key}`);
  const description = group?.description ?? registry.commands.get(node.path)?.description;
  if (description) sections.push(description);

  if (commands.length === 0 && group) {
    sections.push(buildGroupHelp(registry, group).entries.map((entry) => `- \`${entry.path}\``).join('\n'));
  }

  for (const help of commands) {
    sections.push(renderCommandMarkdown(help, 2));
  }

  return `${sections.join('\n\n')}\n`;
}

function renderApiJson(registry: CommandRegistry, rootName: string): string {
  const payload = {
    binary: registry.binary,
    description: registry.description ?? null,
    globalArgs: registry.globalArgs,
    commands: registry.paths.map((path) =>
      buildCommandHelp(registry, registry.commands.get(path) as NonNullable<ReturnType<CommandRegistry['commands']['get']>>, rootName),
    ),
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}

/** Render documentation in memory. Deterministic: same schema, same bytes. */
export function renderDocs(options: GenerateDocsOptions): { files: GeneratedFiles; lint: LintReport | null } {
  const registry = toRegistry(options);
  const rootName = options.rootName ?? 'cli';
  const lint = options.lint === false ? null : lintSchema(registry, options.lint ?? {});

  const files: GeneratedFiles = new Map();
  const nodes = registry.tree.children;

  files.set('README.md', renderIndex(registry, nodes, rootName));
  for (const node of nodes) {
    files.set(fileNameFor(node), renderNodeFile(registry, node, rootName));
  }
  files.set('api.json', renderApiJson(registry, rootName));

  return { files, lint };
}

export interface DocsResult {
  outDir: string;
  written: string[];
  removed: string[];
  lint: LintReport | null;
}

function assertLintOk(lint: LintReport | null): void {
  if (lint && !lint.ok) {
    const details = lint.errors.map((issue) => `  - ${issue.rule} ${issue.target}: ${issue.message}`).join('\n');
    throw new Error(`Refusing to generate documentation; the schema has errors:\n${details}`);
  }
}

/** Generate documentation and write it to disk, replacing the output directory. */
export async function generateDocs(options: GenerateDocsOptions & { outDir: string }): Promise<DocsResult> {
  const { files, lint } = renderDocs(options);
  assertLintOk(lint);

  await rm(options.outDir, { recursive: true, force: true });
  const written: string[] = [];

  for (const [name, content] of files) {
    const target = join(options.outDir, name);
    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
    written.push(name);
  }

  return { outDir: options.outDir, written: written.sort(), removed: [], lint };
}

export interface DocsCheckResult {
  outDir: string;
  /** Files whose content differs from the generated output. */
  stale: string[];
  /** Files that should exist but do not. */
  missing: string[];
  /** Generated-looking files on disk that the schema no longer produces. */
  extra: string[];
  lint: LintReport | null;
  ok: boolean;
}

async function listFiles(dir: string): Promise<string[]> {
  const { readdir } = await import('node:fs/promises');
  const entries = await readdir(dir, { recursive: true, withFileTypes: true }).catch(() => []);
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => relative(dir, join(entry.parentPath ?? dir, entry.name)).split(sep).join('/'));
}

/** Compare generated documentation with what is on disk, without writing anything. */
export async function checkDocs(options: GenerateDocsOptions & { outDir: string }): Promise<DocsCheckResult> {
  const { files, lint } = renderDocs(options);
  const stale: string[] = [];
  const missing: string[] = [];

  for (const [name, content] of files) {
    const target = join(options.outDir, name);
    const existing = await readFile(target, 'utf8').catch(() => null);
    if (existing === null) missing.push(name);
    else if (existing !== content) stale.push(name);
  }

  const onDisk = await listFiles(options.outDir);
  const extra = onDisk.filter((name) => !files.has(name));

  return {
    outDir: options.outDir,
    stale: stale.sort(),
    missing: missing.sort(),
    extra: extra.sort(),
    lint,
    ok: stale.length === 0 && missing.length === 0 && extra.length === 0 && (lint?.ok ?? true),
  };
}
